# Generated by Django 4.2.13 on 2026-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Main counter can receive cash for all pending orders'),
        ),
    ]
