# Generated by Django 4.2.13 on 2026-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='PharmaPOS', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='Rs', max_length=10)),
                ('return_days', models.IntegerField(default=15)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your purchase!')),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacy Settings',
                'verbose_name_plural': 'Pharmacy Settings',
            },
        ),
    ]
